### ISSUE TITLE
Image example

### ISSUE THREAD

**Issue by krypticallusion** [wasabia/flutter_gl#13]
Can you add an example where you use images/videos and manipulate them?

Would be helpful for beginners like me.

Thanks!

**Comment by wasabia** [comment]
Hi @krypticallusion 

no example now, 

for images is same to webgl or opengl   decode image get pixels then upload to texture, use NativeArray for pixels
[https://github.com/wasabia/three_dart/blob/7a62955a2dc98dfddf1d2d18c74fe19ac3fa5657/lib/three3d/renderers/webgl/WebGLTextures.dart#L903](https://github.com/wasabia/three_dart/blob/7a62955a2dc98dfddf1d2d18c74fe19ac3fa5657/lib/three3d/renderers/webgl/WebGLTextures.dart#L903)

videos need write native code decode videos,
you can get share opengl context 
[https://github.com/wasabia/flutter_gl#share-opengl-context-with-flutter_gl](https://github.com/wasabia/flutter_gl#share-opengl-context-with-flutter_gl)

then you can create your opengl context with the share context,
decode video with your context then return Texture,
use Texture with flutter_gl

**Comment by krypticallusion** [comment]
Thanks for the explaination!
