### ISSUE TITLE
Just a question with textures

### ISSUE THREAD

**Issue by deshan** [wasabia/flutter_gl#15]
Hello,
I am working on a project with flutter iOS and android with rendering 2D video texture. Currently creating flutter platform views embedding to flutter and do render in native java/c++ in android and in Objc/c++ in iOS.

I need to check the possibility of using this plugin instead of current native rendering. Here I can pass RGB video data to flutter, and does this plugin ready for 2D projection and render the texture in iOS and Android?

Thanks

**Comment by wasabia** [comment]
[https://github.com/wasabia/flutter_gl#share-opengl-context-with-flutter_gl](https://github.com/wasabia/flutter_gl#share-opengl-context-with-flutter_gl)


render video texture need use share opengl context,
can get flutter_gl shareContext then create yourself opengl context with shareContext,
decode video use you created opengl context and return a texture handle video result
then can use this texture with flutter_gl
