### ISSUE TITLE
gl.bufferData call with too few arguments. Expected: 4 Actual: 3

### ISSUE THREAD

**Issue by George35mk** [wasabia/flutter_gl#2]
I have updated the `flutter_gl` package from `0.0.3` to `0.0.5` and I notice an issue 

I have a code that sets the colors with buffer data but the lib complains about adding one more parameter in `gl.bufferData`.

Code to reproduce 

This is the code that worked before the update.
```dart
setColors(gl) {
    Float32List data = Float32List.fromList([
      Random().nextDouble(), Random().nextDouble(), Random().nextDouble(), 1, //
      Random().nextDouble(), Random().nextDouble(), Random().nextDouble(), 1, //
      Random().nextDouble(), Random().nextDouble(), Random().nextDouble(), 1, //
      Random().nextDouble(), Random().nextDouble(), Random().nextDouble(), 1, //
      Random().nextDouble(), Random().nextDouble(), Random().nextDouble(), 1, //
      Random().nextDouble(), Random().nextDouble(), Random().nextDouble(), 1, //
    ]);

    gl.bufferData(gl.ARRAY_BUFFER, data, gl.STATIC_DRAW);
}
```

and I get this error

```
 OpenGLContextWeb 
{gl: [object WebGL2RenderingContext]}
Error: NoSuchMethodError: 'bufferData'
Dynamic call with too few arguments. Expected: 4 Actual: 3
```

In your example, `ExampleDemoTest.dart` I saw that you provide 4 arguments 

```dart

var vertices = new Float32List.fromList([
    0.0, 0.5,  0.0,  // Vertice #1
   -0.5, -0.5, 0.0, // Vertice #2
    0.5, -0.5, 0.0  // Vertice #3
 ]);

final verticesPtr = calloc<Float>(vertices.length);
verticesPtr.asTypedList(vertices.length).setAll(0, vertices);

gl.bufferData(gl.ARRAY_BUFFER, vertices.length * Float32List.bytesPerElement, verticesPtr, gl.STATIC_DRAW);
```

What do you think we need to provide the size parameter? or it will be better to have it like it was before with only 3 params

now you have this method
```dart
bufferData(int target, int size, data, int usage) {
    gl.glBufferData(target, size, data.cast<Void>(), usage);
}
```

after the change 

```dart
bufferData(int target, data, int usage) {
    late Pointer<Void> nativeData;
    late int size;
    if (data is List<double> || data is Float32List) {
      nativeData = floatListToArrayPointer(data as List<double>).cast();
      size = data.length * sizeOf<Float>();
    } else if (data is Int32List) {
      nativeData = int32ListToArrayPointer(data).cast();
      size = data.length * sizeOf<Int32>();
    } else if (data is Uint16List) {
      nativeData = uInt16ListToArrayPointer(data).cast();
      size = data.length * sizeOf<Uint16>();
    } else if (data is Uint32List) {
      nativeData = uInt32ListToArrayPointer(data).cast();
      size = data.length * sizeOf<Uint32>();  
    } else {
      throw ('bufferData: unsupported native type ${data.runtimeType}');
    }
    gl.glBufferData(target, size, nativeData, usage);
    calloc.free(nativeData);
}
```

I think is better for the user to provide the Float32List and handle all the native code inside the `OpenGLContextES.dart` file as you did before.

Also notice by importing the `dart:ffi` package breaks the web version of the app.

and I get all these errors.

```cmd
flutter run
Multiple devices found:
Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.82
Edge (web)   • edge   • web-javascript • Microsoft Edge 93.0.961.52
[1]: Chrome (chrome)
[2]: Edge (edge)
Please choose one (To quit, press "q/Q"): 1
Launching lib\main.dart on Chrome in debug mode...
lib/engine.dart:6:8: Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^
/G:/Programs/flutter/.pub-cache/hosted/pub.dartlang.org/ffi-1.1.2/lib/src/allocation.dart:5:8: Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^
/G:/Programs/flutter/.pub-cache/hosted/pub.dartlang.org/ffi-1.1.2/lib/src/arena.dart:8:8: Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^
/G:/Programs/flutter/.pub-cache/hosted/pub.dartlang.org/ffi-1.1.2/lib/src/utf8.dart:6:8: Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^
/G:/Programs/flutter/.pub-cache/hosted/pub.dartlang.org/ffi-1.1.2/lib/src/utf16.dart:5:8: Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^
/G:/Programs/flutter/.pub-cache/hosted/pub.dartlang.org/ffi-1.1.2/lib/src/allocation.dart:9:7: Error: Type 'DynamicLibrary' not found.
final DynamicLibrary stdlib = Platform.isWindows
```

also when try to run the app into an android device I get this errors

```cmd
flutter run
Launching lib\main.dart on Lenovo TB J606F in debug mode...

FAILURE: Build failed with an exception.

Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find :threeegl:.
     Searched in the following locations:
     Required by:
         project :app > project :flutter_gl

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
```

Thanks

**Comment by wasabia** [comment]
but when you convert to ptr in bufferData, it need memory copy cost a lot of time.
and if the buffer is big buffer much slower.
if we need update buffer every frame， it is much slower...

so when on app side  we need use ffi

now my solution is define custom Array wrapper dart list to handle app and web
maybe have other good idea, i don't know....

i working implement three.js by Dart base on flutter_gl

later i will release the source code, if you have interest

**Comment by wasabia** [comment]
```
Could not find :threeegl
```

check the example project 
copy the example/android/app/libs/aars/threeegl.aar
to your app android project same path

maybe have some good solution to handle the threeegl.aar

**Comment by George35mk** [comment]
I found some bugs in the code and I want to help you because I need 3D stuff, and the only lib that worked is yours

**Comment by George35mk** [comment]
But I need to understand:
1.  how your package works I don't see any documentation to help me.
2. how you provide the open_gl between android and web you are using some bridge design pattern.
3. The package is OpenGL ES on the android platform and WebGL2 on the web platform?
4. What version of OpenGL ES you are using the v2 or v3.

What is your goal for this package to create a three.js in flutter or a GL wrapper to use in multiple case examples web, android, ios?

**Comment by George35mk** [comment]
In OpenGL-ES.dart file, I see this line `"libGLESv3.so"` where is that file where I can finded?

```dart
DynamicLibrary? getGLLibrary() {
    if (Platform.isAndroid) {
      return DynamicLibrary.open("libGLESv3.so");
    } else {
      return DynamicLibrary.process();
    }
  }
```

**Comment by wasabia** [comment]
"libGLESv3.so" is android built-in library 


[https://flutter.dev/docs/development/platform-integration/c-interop](https://flutter.dev/docs/development/platform-integration/c-interop)

**Comment by wasabia** [comment]
this package is for my three_dart flutter plugin, it is a  three.js implement by Dart plugin.
so it can run with flutter run on web android ios, but webgl is different to OpenGL ES, now it is handled by three_dart

this package have a lot of work to do. 
PR is welcome ....

**Comment by wasabia** [comment]
opengl es version is v3

**Comment by wasabia** [comment]
flutter_gl call  native opengl es api by dart ffi

sorry for my poor english,

it is a litte hard to explanation this package is how work.... 😶 

if you have any problem, i can try explain to you

**Comment by George35mk** [comment]
@wasabia don't worry about your English I understand 👍

**Comment by wasabia** [comment]
simply put

this plugin create two opengles context and the context is share context

one context is bind to flutter plugin side to call flutter api update flutter Texture widget

one context is bind to ffi side so we can draw somthing use dart call ffi, it was draw to FBO

when gl finish the plugin update FBO texture to Texture widget

on web it is simple just use flutter web api same to webgl 

to Smooth out the differences between different platforms，this package wrapper webgl api and opengl es api
