### ISSUE TITLE
iOS deployment target

### ISSUE THREAD

**Issue by intonarumori** [wasabia/flutter_gl#20]
While the plugin did work nicely in a pure Flutter project, when I try to include it a Flutter module, I get the following error:
```
.../ios/Classes/CustomRender.swift:7:8: Compiling for iOS 8.0, but module 'three3d_egl' has a minimum deployment target of iOS 9.0
```

`flutter_gl` podspec defines iOS 8 as the deployment target here:
https://github.com/wasabia/flutter_gl/blob/5963daac6acbd99ffa63e006c4567436232a5463/flutter_gl/ios/flutter_gl.podspec#L20

While `threed3d_egl` requires iOS 9.0 here:
https://github.com/wasabia/three3d_egl/blob/1d428f666319e22ba4b4adab4389d30b41035cc3/three3d_egl.podspec#L20

I think `flutter_gl` podspec needs to be updated to iOS 9.0 as well. What do you think?

**Comment by wasabia** [comment]
👌🏻
