### ISSUE TITLE
Example failing with v0.0.16

### ISSUE THREAD

**Issue by rorySomething** [wasabia/flutter_gl#25]
Hello,
I'm barely getting started...

Trying to use the example triangle code I'm getting errors with FlutterGlPlatform.

`Error: The method 'initialize_interface' isn't defined for the class 'FlutterGlPlatform'.
`
As if it's not seeing anything in flutter_gl_platform_interface-0.0.3/lib/method_channel_flutter_gl.dart.

I'm an absolute beginner with Flutter so I haven't figured out how to try to force the import.

e.g. Adding `import package:flutter_gl_platform_interface/method_channel_flutter_gl.dart';`
did me no good

**Comment by wasabia** [comment]
try 0.0.17

**Comment by wasabia** [comment]
0.0.18 😄

**Comment by rorySomething** [comment]
Excellent, thank you!

After some fiddling with the AndroidManifest it's running.

I hope I can give you useful pushes later as I get building.
