### ISSUE TITLE
Could not find threeegl.aar

### ISSUE THREAD

**Issue by BananaHemic** [wasabia/flutter_gl#27]
First off, thanks for making this repo, I'm really excited to start graphics programming in flutter.

I'm having an issue with building with flutter_gl 0.0.18

FAILURE: Build failed with an exception.
 What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Could not find :threeegl:.
     Searched in the following locations:
       - file:/C:/Users/xyz/myproject/android/app/libs/aars/threeegl.aar
     Required by:
         project :app > project :flutter_gl

I tried manually copying the aar into the project folder where it searched, but that did not work.

Any ideas on what is going wrong? And where can I find the code for the threeegl.aar class?

**Comment by BananaHemic** [comment]
I got it working by copying the threeegl.aar from the example project, instead of copying it from the project files. I am still curious where the code for that file is.

**Comment by wasabia** [comment]
code is simple, just for share opengl context between different flutter plugins, if you no need this feature, you can just ignore it, or remove it?

code is similar to swift
[https://github.com/wasabia/three3d_egl_osx/blob/main/three3d_egl_osx/Classes/three3d_egl_osx.swift](https://github.com/wasabia/three3d_egl_osx/blob/main/three3d_egl_osx/Classes/three3d_egl_osx.swift)

**Comment by BananaHemic** [comment]
Thank you for the reply. That makes sense. If you upload that code, please reopen this with a link so that I can check it out

**Comment by changning420** [comment]
Hello, may I ask how this problem was solved
