### ISSUE TITLE
Question on IOS Context

### ISSUE THREAD

**Issue by BananaHemic** [wasabia/flutter_gl#29]
Hello!

Thanks again for making this useful plugin.

I'm having a hard time understanding how the context is made current on iOS devices. From reading the [source code](https://github.com/wasabia/flutter_gl/blob/0b26584b47dc42328841385fb52c5da544cfea8c/flutter_gl/lib/openGL/opengl/opengl_es_bindings/src/egl_bindings.dart#L737) it looks like dart ffi pulls a reference to "makeCurrent" function.

However, on my ios device, the symbol "makeCurrent" is not found, even though the symbol "glGetIntegerv" is correctly found.

Could you please explain how ios sets the context?

**Comment by wasabia** [comment]
makeCurrent function from three3d_egl [https://github.com/wasabia/flutter_gl/blob/main/flutter_gl/ios/flutter_gl.podspec](https://github.com/wasabia/flutter_gl/blob/main/flutter_gl/ios/flutter_gl.podspec)

**Comment by BananaHemic** [comment]
Thanks! That answered my question
