### ISSUE TITLE
Cannot compile Android app with `flutter_gl` dependency

### ISSUE THREAD

**Issue by intonarumori** [wasabia/flutter_gl#31]
Getting an error why compiling the Android app.

- Added `flutter_gl` to my `pubspec.yaml` as a dependency
- Ran `flutter build apk`

Error message:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkReleaseAarMetadata'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Could not find :threeegl:.
     Searched in the following locations:
       - file:<redacted>/Samples/test3d/android/app/libs/aars/threeegl.aar
     Required by:
         project :app > project :flutter_gl

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

Any ideas what might fix this?

**Comment by intonarumori** [comment]
Just noticed there's a manual step to include the plugin: adding the `threegl.aar`.

Here's the reference to the relevant instructions:
https://github.com/wasabia/flutter_gl/blob/main/flutter_gl/README.md#android-1

**Comment by changning420** [comment]
![image](https://github.com/wasabia/flutter_gl/assets/12890890/41c45829-d817-41d4-b0b9-58e93cb78171)
How was the problem solved? I have the same problem.
https://github.com/wasabia/flutter_gl/blob/main/flutter_gl/README.md#android-1 ,this is not work.
