### ISSUE TITLE
Instruction for developers & line width

### ISSUE THREAD

**Issue by GlebEfremovfff** [wasabia/flutter_gl#43]
Hello! Could you create an instruction how to use all methods from gl? And can you help me pls with line width? When I write "_gl.lineWidth(5);" width doesn't change:(

**Comment by pelaezcarlos** [comment]
Hi, we have a similar problem with the lines width, modifying the material:

var linematerial = three.LineBasicMaterial({
      "color": 0xffffff,
      "linewidth": 8,

On Android it works fine, but Win/MAC/Web doesn't
