### ISSUE TITLE
Desktop support

### ISSUE THREAD

**Issue by mariuszmaximus** [wasabia/flutter_gl#6]
Do you have a plan to add a Desktop platform? https://docs.flutter.dev/desktop ?
Is that a big problem?

**Comment by wasabia** [comment]
I want to support desktop but i have no experience on desktop. 😭 
if you have interest welcome pull request.

**Comment by wasabia** [comment]
flutter_gl_macos  had update to github.
but it still have a problem, now it only can draw to fbo with dart, but can not updateTexture to flutter....
need help...

**Comment by wasabia** [comment]
it looks like macos opengl context setup is not work, i have no idea now. 


anyway we can make it work without opengl context.
just read pixels, then convert pixels to CVPixelsBuffer ??? maybe have performance problem??

**Comment by wasabia** [comment]
now we can update texture to flutter on macos

**Comment by mariuszmaximus** [comment]
I confirm ! it works !

**Comment by wasabia** [comment]
maybe still have api not added, welcome PR ISSUE
