### ISSUE TITLE
How to get GL_VENDOR and GL_RERENDER from GL10 in Android project MainAcitivity

### ISSUE THREAD

**Issue by helloo0-0oword** [wasabia/flutter_gl#7]
Thanks for your library. Does it bother me when I have a side question?. I am having a problem, I want to get GL_VENDOR and GL_RERENDER from GL10 in MainActivity, how do I do that?

Thank you so much <3

<img width="856" alt="Screen Shot 2021-12-22 at 22 36 52" src="https://user-images.githubusercontent.com/32776884/147117147-33e4b15f-161c-410d-aefd-05763aa448cb.png">
3

**Comment by wasabia** [comment]
why you call opengl api use java? if you use this library, you should call opengl api use dart....

**Comment by helloo0-0oword** [comment]
I just want to get the above 2 information through the file MainActivity. Can you help me ? :(

**Comment by wasabia** [comment]
maybe you should set opengl context first

**Comment by helloo0-0oword** [comment]
hmm. Do you have any examples of this? I tried searching but still can't find how to use it @@

**Comment by helloo0-0oword** [comment]
hey, i have another question. Can i get this information when i use this library ?

**Comment by wasabia** [comment]
you can use getString

use flutter_gl from github

```
    print( _gl.getString(_gl.VENDOR) );
    print( _gl.getString(_gl.RENDERER) );

```

**Comment by helloo0-0oword** [comment]
> you can use getString
> 
> use flutter_gl from github
> 
> ```
>     print( _gl.getString(_gl.VENDOR) );
>     print( _gl.getString(_gl.RENDERER) );
> ```

Thank you <3
